<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NestedException\NestedException.csproj" />
    <ProjectReference Include="..\Shared\SharedLibrary.csproj" />
  </ItemGroup>
    
</Project>
